api: TypeString
api_config: TypeString
condition:
    description: TypeString
    expression: TypeString
    title: TypeString
etag: TypeString
members: TypeSet(TypeString)
project: TypeString
role: TypeString

