condition:
    description: TypeString
    expression: TypeString
    title: TypeString
etag: TypeString
location: TypeString
member: TypeString
project: TypeString
role: TypeString
workstation_cluster_id: TypeString
workstation_config_id: TypeString

