data_refresh_window_days:
    Type: TypeInt
    Description: |-
        The number of days to look back to automatically refresh the data.
        For example, if dataRefreshWindowDays = 10, then every day BigQuery
        reingests data for [today-10, today-1], rather than ingesting data for
        just [today-1]. Only valid if the data source supports the feature.
        Set the value to 0 to use the default value.
    Optional: "true"
data_source_id:
    Type: TypeString
    Description: The data source id. Cannot be changed once the transfer config is created.
    Required: "true"
destination_dataset_id:
    Type: TypeString
    Description: The BigQuery target dataset id.
    Optional: "true"
disabled:
    Type: TypeBool
    Description: When set to true, no runs are scheduled for a given transfer.
    Optional: "true"
display_name:
    Type: TypeString
    Description: The user specified display name for the transfer config.
    Required: "true"
email_preferences:
    Type: TypeList
    Description: |-
        Email notifications will be sent according to these preferences to the
        email address of the user who owns this transfer config.
    Optional: "true"
    MaxItems: "1"
    Properties:
        enable_failure_email:
            Type: TypeBool
            Description: If true, email notifications will be sent on transfer run failures.
            Required: "true"
location:
    Type: TypeString
    Description: |-
        The geographic location where the transfer config should reside.
        Examples: US, EU, asia-northeast1. The default value is US.
    Optional: "true"
name:
    Type: TypeString
    Description: |-
        The resource name of the transfer config. Transfer config names have the
        form projects/{projectId}/locations/{location}/transferConfigs/{configId}
        or projects/{projectId}/transferConfigs/{configId},
        where configId is usually a uuid, but this is not required.
        The name is ignored when creating a transfer config.
    Computed: "true"
notification_pubsub_topic:
    Type: TypeString
    Description: |-
        Pub/Sub topic where notifications will be sent after transfer runs
        associated with this transfer config finish.
    Optional: "true"
params:
    Type: TypeMap
    Description: |-
        Parameters specific to each data source. For more information see the bq tab in the 'Setting up a data transfer'
        section for each data source. For example the parameters for Cloud Storage transfers are listed here:
        https://cloud.google.com/bigquery-transfer/docs/cloud-storage-transfer#bq

        **NOTE** : If you are attempting to update a parameter that cannot be updated (due to api limitations) [please force recreation of the resource](https://www.terraform.io/cli/state/taint#forcing-re-creation-of-resources).
    Required: "true"
project:
    Type: TypeString
    Computed: "true"
    Optional: "true"
schedule:
    Type: TypeString
    Description: |-
        Data transfer schedule. If the data source does not support a custom
        schedule, this should be empty. If it is empty, the default value for
        the data source will be used. The specified times are in UTC. Examples
        of valid format: 1st,3rd monday of month 15:30, every wed,fri of jan,
        jun 13:15, and first sunday of quarter 00:00. See more explanation
        about the format here:
        https://cloud.google.com/appengine/docs/flexible/python/scheduling-jobs-with-cron-yaml#the_schedule_format
        NOTE: the granularity should be at least 8 hours, or less frequent.
    Optional: "true"
schedule_options:
    Type: TypeList
    Description: Options customizing the data transfer schedule.
    Optional: "true"
    MaxItems: "1"
    Properties:
        disable_auto_scheduling:
            Type: TypeBool
            Description: |-
                If true, automatic scheduling of data transfer runs for this
                configuration will be disabled. The runs can be started on ad-hoc
                basis using transferConfigs.startManualRuns API. When automatic
                scheduling is disabled, the TransferConfig.schedule field will
                be ignored.
            Optional: "true"
            AtLeastOneOf: schedule_options.0.disable_auto_scheduling, schedule_options.0.start_time, schedule_options.0.end_time
        end_time:
            Type: TypeString
            Description: |-
                Defines time to stop scheduling transfer runs. A transfer run cannot be
                scheduled at or after the end time. The end time can be changed at any
                moment. The time when a data transfer can be triggered manually is not
                limited by this option.
            Optional: "true"
            AtLeastOneOf: schedule_options.0.disable_auto_scheduling, schedule_options.0.start_time, schedule_options.0.end_time
        start_time:
            Type: TypeString
            Description: |-
                Specifies time to start scheduling transfer runs. The first run will be
                scheduled at or after the start time according to a recurrence pattern
                defined in the schedule string. The start time can be changed at any
                moment. The time when a data transfer can be triggered manually is not
                limited by this option.
            Optional: "true"
            AtLeastOneOf: schedule_options.0.disable_auto_scheduling, schedule_options.0.start_time, schedule_options.0.end_time
sensitive_params:
    Type: TypeList
    Description: |-
        Different parameters are configured primarily using the the 'params' field on this
        resource. This block contains the parameters which contain secrets or passwords so that they can be marked
        sensitive and hidden from plan output. The name of the field, eg: secret_access_key, will be the key
        in the 'params' map in the api request.

        Credentials may not be specified in both locations and will cause an error. Changing from one location
        to a different credential configuration in the config will require an apply to update state.
    Optional: "true"
    MaxItems: "1"
    Properties:
        secret_access_key:
            Type: TypeString
            Description: The Secret Access Key of the AWS account transferring data from.
            Required: "true"
service_account_name:
    Type: TypeString
    Description: |-
        Service account email. If this field is set, transfer config will
        be created with this service account credentials. It requires that
        requesting user calling this API has permissions to act as this service account.
    Optional: "true"

