audit_log_config:
    Type: TypeSet
    Description: The configuration for logging of each type of permission. This can be specified multiple times.
    Required: "true"
    Properties:
        exempted_members:
            Type: TypeSet
            Description: 'Identities that do not cause logging for this type of permission. Each entry can have one of the following values:user:{emailid}: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com. serviceAccount:{emailid}: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com. group:{emailid}: An email address that represents a Google group. For example, admins@example.com. domain:{domain}: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.'
            Optional: "true"
        log_type:
            Type: TypeString
            Description: Permission type for which logging is to be configured. Must be one of DATA_READ, DATA_WRITE, or ADMIN_READ.
            Required: "true"
etag:
    Type: TypeString
    Description: The etag of iam policy
    Computed: "true"
org_id:
    Type: TypeString
    Description: The numeric ID of the organization in which you want to manage the audit logging config.
    Required: "true"
service:
    Type: TypeString
    Description: Service which will be enabled for audit logging. The special value allServices covers all services.
    Required: "true"

