annotations:
    Type: TypeMap
    Description: |-
        Optional. User annotations. These attributes can only be set and used by the user, and not by Cloud Deploy. Annotations must meet the following constraints: * Annotations are key/value pairs. * Valid annotation keys have two segments: an optional prefix and name, separated by a slash ('/'). * The name segment is required and must be 63 characters or less, beginning and ending with an alphanumeric character ('[a-z0-9A-Z]') with dashes ('-'), underscores ('_'), dots ('.'), and alphanumerics between. * The prefix is optional. If specified, the prefix must be a DNS subdomain: a series of DNS labels separated by dots('.'), not longer than 253 characters in total, followed by a slash ('/'). See https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set for more details.

        **Note**: This field is non-authoritative, and will only manage the annotations present in your configuration.
        Please refer to the field 'effective_annotations' for all of the annotations present on the resource.
    Optional: "true"
create_time:
    Type: TypeString
    Description: Output only. Time at which the automation was created.
    Computed: "true"
delivery_pipeline:
    Type: TypeString
    Description: The delivery_pipeline for the resource
    Required: "true"
description:
    Type: TypeString
    Description: Optional. Description of the 'Automation'. Max length is 255 characters.
    Optional: "true"
effective_annotations:
    Type: TypeMap
    Description: All of annotations (key/value pairs) present on the resource in GCP, including the annotations configured through Terraform, other clients and services.
    Computed: "true"
effective_labels:
    Type: TypeMap
    Description: All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.
    Computed: "true"
etag:
    Type: TypeString
    Description: Optional. The weak etag of the 'Automation' resource. This checksum is computed by the server based on the value of other fields, and may be sent on update and delete requests to ensure the client has an up-to-date value before proceeding.
    Computed: "true"
labels:
    Type: TypeMap
    Description: |-
        Optional. Labels are attributes that can be set and used by both the user and by Cloud Deploy. Labels must meet the following constraints: * Keys and values can contain only lowercase letters, numeric characters, underscores, and dashes. * All characters must use UTF-8 encoding, and international characters are allowed. * Keys must start with a lowercase letter or international character. * Each resource is limited to a maximum of 64 labels. Both keys and values are additionally constrained to be <= 63 characters.

        **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
        Please refer to the field 'effective_labels' for all of the labels present on the resource.
    Optional: "true"
location:
    Type: TypeString
    Description: The location for the resource
    Required: "true"
name:
    Type: TypeString
    Description: Name of the 'Automation'.
    Required: "true"
project:
    Type: TypeString
    Computed: "true"
    Optional: "true"
rules:
    Type: TypeList
    Description: 'Required. List of Automation rules associated with the Automation resource. Must have at least one rule and limited to 250 rules per Delivery Pipeline. Note: the order of the rules here is not the same as the order of execution.'
    Required: "true"
    Properties:
        advance_rollout_rule:
            Type: TypeList
            Description: Optional. The 'AdvanceRolloutRule' will automatically advance a successful Rollout.
            Optional: "true"
            MaxItems: "1"
            Properties:
                id:
                    Type: TypeString
                    Description: Required. ID of the rule. This id must be unique in the 'Automation' resource to which this rule belongs. The format is 'a-z{0,62}'.
                    Required: "true"
                source_phases:
                    Type: TypeList
                    Description: 'Optional. Proceeds only after phase name matched any one in the list. This value must consist of lower-case letters, numbers, and hyphens, start with a letter and end with a letter or a number, and have a max length of 63 characters. In other words, it must match the following regex: ''^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$''.'
                    Optional: "true"
                wait:
                    Type: TypeString
                    Description: Optional. How long to wait after a rollout is finished.
                    Optional: "true"
        promote_release_rule:
            Type: TypeList
            Description: Optional. 'PromoteReleaseRule' will automatically promote a release from the current target to a specified target.
            Optional: "true"
            MaxItems: "1"
            Properties:
                destination_phase:
                    Type: TypeString
                    Description: Optional. The starting phase of the rollout created by this operation. Default to the first phase.
                    Optional: "true"
                destination_target_id:
                    Type: TypeString
                    Description: 'Optional. The ID of the stage in the pipeline to which this ''Release'' is deploying. If unspecified, default it to the next stage in the promotion flow. The value of this field could be one of the following: * The last segment of a target name. It only needs the ID to determine if the target is one of the stages in the promotion sequence defined in the pipeline. * "@next", the next target in the promotion sequence.'
                    Optional: "true"
                id:
                    Type: TypeString
                    Description: Required. ID of the rule. This id must be unique in the 'Automation' resource to which this rule belongs. The format is 'a-z{0,62}'.
                    Required: "true"
                wait:
                    Type: TypeString
                    Description: Optional. How long the release need to be paused until being promoted to the next target.
                    Optional: "true"
selector:
    Type: TypeList
    Description: Required. Selected resources to which the automation will be applied.
    Required: "true"
    MaxItems: "1"
    Properties:
        targets:
            Type: TypeList
            Description: Contains attributes about a target.
            Required: "true"
            Properties:
                id:
                    Type: TypeString
                    Description: 'ID of the ''Target''. The value of this field could be one of the following: * The last segment of a target name. It only needs the ID to determine which target is being referred to * "*", all targets in a location.'
                    Optional: "true"
                labels:
                    Type: TypeMap
                    Description: Target labels.
                    Computed: "true"
                    Optional: "true"
service_account:
    Type: TypeString
    Description: Required. Email address of the user-managed IAM service account that creates Cloud Deploy release and rollout resources.
    Required: "true"
suspended:
    Type: TypeBool
    Description: Optional. When Suspended, automation is deactivated from execution.
    Optional: "true"
terraform_labels:
    Type: TypeMap
    Description: |-
        The combination of labels configured directly on the resource
         and default labels configured on the provider.
    Computed: "true"
uid:
    Type: TypeString
    Description: Output only. Unique identifier of the 'Automation'.
    Computed: "true"
update_time:
    Type: TypeString
    Description: Output only. Time at which the automation was updated.
    Computed: "true"

