active_key_version:
    Type: TypeString
    Description: |-
        The asymmetric crypto key version to use for signing approval requests.
        Empty active_key_version indicates that a Google-managed key should be used for signing.
    Optional: "true"
ancestor_has_active_key_version:
    Type: TypeBool
    Description: This field will always be unset for the organization since organizations do not have ancestors.
    Computed: "true"
enrolled_ancestor:
    Type: TypeBool
    Description: This field will always be unset for the organization since organizations do not have ancestors.
    Computed: "true"
enrolled_services:
    Type: TypeSet
    Description: |-
        A list of Google Cloud Services for which the given resource has Access Approval enrolled.
        Access requests for the resource given by name against any of these services contained here will be required
        to have explicit approval. Enrollment can be done for individual services.

        A maximum of 10 enrolled services will be enforced, to be expanded as the set of supported services is expanded.
    Required: "true"
    Properties:
        cloud_product:
            Type: TypeString
            Description: |-
                The product for which Access Approval will be enrolled. Allowed values are listed (case-sensitive):
                  all
                  appengine.googleapis.com
                  bigquery.googleapis.com
                  bigtable.googleapis.com
                  cloudkms.googleapis.com
                  compute.googleapis.com
                  dataflow.googleapis.com
                  iam.googleapis.com
                  pubsub.googleapis.com
                  storage.googleapis.com
            Required: "true"
        enrollment_level:
            Type: TypeString
            Description: 'The enrollment level of the service. Default value: "BLOCK_ALL" Possible values: ["BLOCK_ALL"]'
            Optional: "true"
invalid_key_version:
    Type: TypeBool
    Description: |-
        If the field is true, that indicates that there is some configuration issue with the active_key_version
        configured on this Organization (e.g. it doesn't exist or the Access Approval service account doesn't have the
        correct permissions on it, etc.).
    Computed: "true"
name:
    Type: TypeString
    Description: The resource name of the settings. Format is "organizations/{organization_id}/accessApprovalSettings"
    Computed: "true"
notification_emails:
    Type: TypeSet
    Description: |-
        A list of email addresses to which notifications relating to approval requests should be sent.
        Notifications relating to a resource will be sent to all emails in the settings of ancestor
        resources of that resource. A maximum of 50 email addresses are allowed.
    Computed: "true"
    Optional: "true"
    MaxItems: "50"
organization_id:
    Type: TypeString
    Description: ID of the organization of the access approval settings.
    Required: "true"

