api:
    Type: TypeString
    Description: The API to attach the config to.
    Required: "true"
api_config_id:
    Type: TypeString
    Description: Identifier to assign to the API Config. Must be unique within scope of the parent resource(api).
    Computed: "true"
    Optional: "true"
api_config_id_prefix:
    Type: TypeString
    Description: Creates a unique name beginning with the specified prefix. If this and api_config_id are unspecified, a random value is chosen for the name.
    Computed: "true"
    Optional: "true"
    ConflictsWith: api_config_id
display_name:
    Type: TypeString
    Description: A user-visible name for the API.
    Computed: "true"
    Optional: "true"
effective_labels:
    Type: TypeMap
    Description: All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.
    Computed: "true"
gateway_config:
    Type: TypeList
    Description: |-
        Immutable. Gateway specific configuration.
        If not specified, backend authentication will be set to use OIDC authentication using the default compute service account
    Optional: "true"
    MaxItems: "1"
    Properties:
        backend_config:
            Type: TypeList
            Description: Backend settings that are applied to all backends of the Gateway.
            Required: "true"
            MaxItems: "1"
            Properties:
                google_service_account:
                    Type: TypeString
                    Description: |-
                        Google Cloud IAM service account used to sign OIDC tokens for backends that have authentication configured
                        (https://cloud.google.com/service-infrastructure/docs/service-management/reference/rest/v1/services.configs#backend).
                    Required: "true"
grpc_services:
    Type: TypeList
    Description: gRPC service definition files. If specified, openapiDocuments must not be included.
    Optional: "true"
    RequiredWith: managed_service_configs
    ExactlyOneOf: openapi_documents, grpc_services
    Properties:
        file_descriptor_set:
            Type: TypeList
            Description: |-
                Input only. File descriptor set, generated by protoc.
                To generate, use protoc with imports and source info included. For an example test.proto file, the following command would put the value in a new file named out.pb.

                $ protoc --include_imports --include_source_info test.proto -o out.pb
            Required: "true"
            MaxItems: "1"
            Properties:
                contents:
                    Type: TypeString
                    Description: Base64 encoded content of the file.
                    Required: "true"
                path:
                    Type: TypeString
                    Description: The file path (full or relative path). This is typically the path of the file when it is uploaded.
                    Required: "true"
        source:
            Type: TypeList
            Description: Uncompiled proto files associated with the descriptor set, used for display purposes (server-side compilation is not supported). These should match the inputs to 'protoc' command used to generate fileDescriptorSet.
            Optional: "true"
            Properties:
                contents:
                    Type: TypeString
                    Description: Base64 encoded content of the file.
                    Required: "true"
                path:
                    Type: TypeString
                    Description: The file path (full or relative path). This is typically the path of the file when it is uploaded.
                    Required: "true"
labels:
    Type: TypeMap
    Description: |-
        Resource labels to represent user-provided metadata.


        **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
        Please refer to the field 'effective_labels' for all of the labels present on the resource.
    Optional: "true"
managed_service_configs:
    Type: TypeList
    Description: |-
        Optional. Service Configuration files. At least one must be included when using gRPC service definitions. See https://cloud.google.com/endpoints/docs/grpc/grpc-service-config#service_configuration_overview for the expected file contents.
        If multiple files are specified, the files are merged with the following rules: * All singular scalar fields are merged using "last one wins" semantics in the order of the files uploaded. * Repeated fields are concatenated. * Singular embedded messages are merged using these rules for nested fields.
    Optional: "true"
    RequiredWith: grpc_services
    Properties:
        contents:
            Type: TypeString
            Description: Base64 encoded content of the file.
            Required: "true"
        path:
            Type: TypeString
            Description: The file path (full or relative path). This is typically the path of the file when it is uploaded.
            Required: "true"
name:
    Type: TypeString
    Description: The resource name of the API Config.
    Computed: "true"
openapi_documents:
    Type: TypeList
    Description: OpenAPI specification documents. If specified, grpcServices and managedServiceConfigs must not be included.
    Optional: "true"
    ExactlyOneOf: openapi_documents, grpc_services
    Properties:
        document:
            Type: TypeList
            Description: The OpenAPI Specification document file.
            Required: "true"
            MaxItems: "1"
            Properties:
                contents:
                    Type: TypeString
                    Description: Base64 encoded content of the file.
                    Required: "true"
                path:
                    Type: TypeString
                    Description: The file path (full or relative path). This is typically the path of the file when it is uploaded.
                    Required: "true"
project:
    Type: TypeString
    Computed: "true"
    Optional: "true"
service_config_id:
    Type: TypeString
    Description: The ID of the associated Service Config (https://cloud.google.com/service-infrastructure/docs/glossary#config).
    Computed: "true"
terraform_labels:
    Type: TypeMap
    Description: |-
        The combination of labels configured directly on the resource
         and default labels configured on the provider.
    Computed: "true"

